repos:
- repo: https://github.com/tofuutils/pre-commit-opentofu
  rev: v2.2.2 # Get the latest from: https://github.com/tofuutils/pre-commit-opentofu/releases
  hooks:
    - id: tofu_fmt
    - id: tofu_docs
